-- Schemas — one per service. Services only access their own schema.
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS notes;
CREATE SCHEMA IF NOT EXISTS habits;
CREATE SCHEMA IF NOT EXISTS content;
CREATE SCHEMA IF NOT EXISTS analytics;
CREATE SCHEMA IF NOT EXISTS games;
CREATE SCHEMA IF NOT EXISTS llm;
CREATE SCHEMA IF NOT EXISTS jobs;

-- Per-service DB users (passwords are for local dev only; set via env in prod)
DO $$ BEGIN CREATE USER gateway_svc  WITH PASSWORD 'gateway_dev';  EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE USER notes_svc    WITH PASSWORD 'notes_dev';    EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE USER habits_svc   WITH PASSWORD 'habits_dev';   EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE USER content_svc  WITH PASSWORD 'content_dev';  EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE USER analytics_svc WITH PASSWORD 'analytics_dev'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE USER games_svc    WITH PASSWORD 'games_dev';    EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE USER llm_svc      WITH PASSWORD 'llm_dev';      EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE USER jobs_svc     WITH PASSWORD 'jobs_dev';     EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Grant each user access only to its own schema
GRANT USAGE ON SCHEMA auth      TO gateway_svc;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA auth      TO gateway_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth      GRANT ALL ON TABLES TO gateway_svc;

GRANT USAGE ON SCHEMA notes     TO notes_svc;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA notes     TO notes_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA notes     GRANT ALL ON TABLES TO notes_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA notes     GRANT ALL ON SEQUENCES TO notes_svc;

GRANT USAGE ON SCHEMA habits    TO habits_svc;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA habits    TO habits_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA habits    GRANT ALL ON TABLES TO habits_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA habits    GRANT ALL ON SEQUENCES TO habits_svc;

GRANT USAGE ON SCHEMA content   TO content_svc;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA content   TO content_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA content   GRANT ALL ON TABLES TO content_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA content   GRANT ALL ON SEQUENCES TO content_svc;

GRANT USAGE ON SCHEMA analytics TO analytics_svc;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA analytics TO analytics_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT ALL ON TABLES TO analytics_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT ALL ON SEQUENCES TO analytics_svc;

GRANT USAGE ON SCHEMA games     TO games_svc;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA games     TO games_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA games     GRANT ALL ON TABLES TO games_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA games     GRANT ALL ON SEQUENCES TO games_svc;

GRANT USAGE ON SCHEMA llm       TO llm_svc;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA llm       TO llm_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA llm       GRANT ALL ON TABLES TO llm_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA llm       GRANT ALL ON SEQUENCES TO llm_svc;

GRANT USAGE ON SCHEMA jobs      TO jobs_svc;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA jobs      TO jobs_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA jobs      GRANT ALL ON TABLES TO jobs_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA jobs      GRANT ALL ON SEQUENCES TO jobs_svc;
